/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockToken__factory } from "./MockToken__factory";
export { StakingContract__factory } from "./StakingContract__factory";
